//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLEF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class NorthwindEntities : DbContext
    {
        public NorthwindEntities()
            : base("name=NorthwindEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Products> Products { get; set; }
    
        public virtual ObjectResult<VentaGetByIdProducto_Result> VentaGetByIdProducto()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VentaGetByIdProducto_Result>("VentaGetByIdProducto");
        }
    
        public virtual ObjectResult<f_ProductoPruebaGetAll_Result> f_ProductoPruebaGetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<f_ProductoPruebaGetAll_Result>("f_ProductoPruebaGetAll");
        }
    
        public virtual ObjectResult<ProductoPruebaGetAll_Result> ProductoPruebaGetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProductoPruebaGetAll_Result>("ProductoPruebaGetAll");
        }
    }
}
